version: '3.8'

services:
  nestapp:
    image: valentinojcarrero/alltagsauto:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: