const usersExample = [
  {
      id: 1,
      photo: "https://randomuser.me/api/portraits/men/32.jpg",
      text: "Das Mieten eines Luxusautos bei Alltagsauto-Exclusive war eine fantastische Erfahrung! Der Service war erstklassig und das Auto war in perfektem Zustand.",
      name: "Patrik",
      surname: "Müller",
      email: "MullerPatrik27@email.ch",
      city: "Zürich",
  },
  {
      id: 2,
      photo: "https://randomuser.me/api/portraits/women/94.jpg",
      text: "Ein Luxusauto bei Alltagsauto-Exclusive zu mieten hat meinen Urlaub unvergesslich gemacht. Der Fahrspaß und der Komfort waren einfach unschlagbar.",
      name: "Anna",
      surname: "Schmidt",
      email: "AnnaSchmidt_327@mail.ch",
      city: "Bern",
  },
  {
      id: 3,
      photo: "https://randomuser.me/api/portraits/men/42.jpg",
      text: "Ich habe noch nie ein so großartiges Fahrerlebnis gehabt. Das Luxusauto von Alltagsauto-Exclusive war makellos und der Service hervorragend.",
      name: "Carl",
      surname: "Fischer",
      email: "PFischer94@mail.com",
      city: "Basel",
  },
  {
      id: 4,
      photo: "https://randomuser.me/api/portraits/men/43.jpg",
      text: "Der Luxuswagen war in einem tadellosen Zustand und der Service von Alltagsauto-Exclusive war ausgezeichnet.",
      name: "Peter",
      surname: "Weber",
      email: "PeterWeber123@mail.ch",
      city: "Luzern",
  },
  {
      id: 5,
      photo: "https://randomuser.me/api/portraits/women/95.jpg",
      text: "Ich war sehr zufrieden mit dem Service und dem Auto. Ich werde Alltagsauto-Exclusive auf jeden Fall wieder nutzen.",
      name: "Sandra",
      surname: "Huber",
      email: "SandraHuber567@mail.ch",
      city: "Genf",
  },
  {
      id: 6,
      photo: "https://randomuser.me/api/portraits/men/44.jpg",
      text: "Ein wirklich erstklassiger Service und ein fantastisches Auto. Ich kann Alltagsauto-Exclusive nur empfehlen.",
      name: "Thomas",
      surname: "Meier",
      email: "ThomasMeier_99@mail.ch",
      city: "Winterthur",
  },
  {
      id: 7,
      photo: "https://randomuser.me/api/portraits/women/96.jpg",
      text: "Die Erfahrung mit Alltagsauto-Exclusive war hervorragend. Das Auto war ein Traum.",
      name: "Laura",
      surname: "Moser",
      email: "LauraMoser78@mail.ch",
      city: "St. Gallen",
  },
  {
      id: 8,
      photo: "https://randomuser.me/api/portraits/men/45.jpg",
      text: "Der Service war ausgezeichnet und das Auto in perfektem Zustand. Ich werde definitiv wieder bei Alltagsauto-Exclusive mieten.",
      name: "Markus",
      surname: "Berger",
      email: "MarkusBerger_53@mail.ch",
      city: "Lugano",
  },
  {
      id: 9,
      photo: "https://randomuser.me/api/portraits/women/97.jpg",
      text: "Alltagsauto-Exclusive hat meinen Urlaub durch das Luxusauto unvergesslich gemacht. Der Service war top.",
      name: "Julia",
      surname: "Roth",
      email: "JuliaRoth_88@mail.ch",
      city: "Fribourg",
  },
  {
      id: 10,
      photo: "https://randomuser.me/api/portraits/men/46.jpg",
      text: "Ich war beeindruckt von der Qualität des Autos und dem hervorragenden Service von Alltagsauto-Exclusive.",
      name: "Daniel",
      surname: "Schneider",
      email: "DanielSchneider_12@mail.ch",
      city: "Lausanne",
  },
  {
      id: 11,
      photo: "https://randomuser.me/api/portraits/women/98.jpg",
      text: "Das Mieten eines Luxuswagens war eine tolle Erfahrung. Der Service war sehr gut und das Auto perfekt.",
      name: "Nina",
      surname: "Wagner",
      email: "NinaWagner_33@mail.ch",
      city: "Zug",
  },
  {
      id: 12,
      photo: "https://randomuser.me/api/portraits/men/47.jpg",
      text: "Alltagsauto-Exclusive hat mir eine großartige Erfahrung beschert. Das Auto war makellos und der Service professionell.",
      name: "Stefan",
      surname: "Keller",
      email: "StefanKeller_90@mail.ch",
      city: "Thun",
  },
  {
      id: 13,
      photo: "https://randomuser.me/api/portraits/women/99.jpg",
      text: "Das Auto war in einem einwandfreien Zustand und der Service von Alltagsauto-Exclusive war hervorragend.",
      name: "Lena",
      surname: "Hofmann",
      email: "LenaHofmann_45@mail.ch",
      city: "Biel",
  },
  {
      id: 14,
      photo: "https://randomuser.me/api/portraits/men/48.jpg",
      text: "Ich bin sehr zufrieden mit dem Service und dem Fahrzeug. Alltagsauto-Exclusive hat meine Erwartungen übertroffen.",
      name: "Michael",
      surname: "Baumann",
      email: "MichaelBaumann_72@mail.ch",
      city: "Chur",
  },
  {
      id: 15,
      photo: "https://randomuser.me/api/portraits/women/100.jpg",
      text: "Ein tolles Erlebnis von Anfang bis Ende. Der Luxuswagen war perfekt und der Service ausgezeichnet.",
      name: "Sophie",
      surname: "Frei",
      email: "SophieFrei_23@mail.ch",
      city: "Neuenburg",
  },
  {
      id: 16,
      photo: "https://randomuser.me/api/portraits/men/49.jpg",
      text: "Das Mieten eines Luxusautos war einfach und unkompliziert. Der Service war erstklassig und das Auto war in einem hervorragenden Zustand.",
      name: "Johann",
      surname: "Zimmermann",
      email: "JohannZimmermann_67@mail.ch",
      city: "Sion",
  },
  {
      id: 17,
      photo: "https://randomuser.me/api/portraits/women/101.jpg",
      text: "Ich kann Alltagsauto-Exclusive nur empfehlen. Der Service war hervorragend und das Auto war ein Traum.",
      name: "Maria",
      surname: "Brunner",
      email: "MariaBrunner_19@mail.ch",
      city: "Schaffhausen",
  },
  {
      id: 18,
      photo: "https://randomuser.me/api/portraits/men/50.jpg",
      text: "Ein erstklassiger Service und ein fantastisches Auto. Alltagsauto-Exclusive hat meinen Urlaub unvergesslich gemacht.",
      name: "Christian",
      surname: "Graf",
      email: "ChristianGraf_84@mail.ch",
      city: "Solothurn",
  },
  {
      id: 19,
      photo: "https://randomuser.me/api/portraits/women/102.jpg",
      text: "Ich war begeistert vom Service und dem Luxusauto. Ich werde Alltagsauto-Exclusive definitiv weiterempfehlen.",
      name: "Martina",
      surname: "Schwarz",
      email: "MartinaSchwarz_22@mail.ch",
      city: "Herisau",
  },
  {
      id: 20,
      photo: "https://randomuser.me/api/portraits/men/51.jpg",
      text: "Der Luxuswagen war in perfektem Zustand und der Service war ausgezeichnet. Eine wirklich tolle Erfahrung.",
      name: "Andreas",
      surname: "Walter",
      email: "AndreasWalter_54@mail.ch",
      city: "Baden",
  },
  {
      id: 21,
      photo: "https://randomuser.me/api/portraits/women/103.jpg",
      text: "Ein tolles Erlebnis von Anfang bis Ende. Der Service war sehr gut und das Auto war fantastisch.",
      name: "Ursula",
      surname: "Koch",
      email: "UrsulaKoch_30@mail.ch",
      city: "Wettingen",
  },
  {
      id: 22,
      photo: "https://randomuser.me/api/portraits/men/52.jpg",
      text: "Das Mieten eines Luxuswagens war eine fantastische Erfahrung. Der Service war hervorragend und das Auto war perfekt.",
      name: "Hans",
      surname: "Lang",
      email: "HansLang_78@mail.ch",
      city: "Rapperswil",
  },
  {
      id: 23,
      photo: "https://randomuser.me/api/portraits/women/104.jpg",
      text: "Der Service von Alltagsauto-Exclusive war erstklassig und das Auto in einem perfekten Zustand. Eine wirklich tolle Erfahrung.",
      name: "Sabine",
      surname: "Kuhn",
      email: "SabineKuhn_46@mail.ch",
      city: "Yverdon",
  },
  {
      id: 24,
      photo: "https://randomuser.me/api/portraits/men/53.jpg",
      text: "Ein hervorragender Service und ein fantastisches Auto. Alltagsauto-Exclusive hat meinen Urlaub unvergesslich gemacht.",
      name: "Ralf",
      surname: "Krämer",
      email: "RalfKraemer_91@mail.ch",
      city: "Wetzikon",
  },
  {
      id: 25,
      photo: "https://randomuser.me/api/portraits/women/105.jpg",
      text: "Das Mieten eines Luxusautos war eine großartige Erfahrung. Der Service war hervorragend und das Auto war perfekt.",
      name: "Katrin",
      surname: "Schulz",
      email: "KatrinSchulz_53@mail.ch",
      city: "Olten",
  }
];

export default usersExample;
